---
title: "Udacity Bikeshare Project"
author: "Christina Lopez"
date: "7/1/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r project}

## Question 1##
### What is the most popular day of the week to rent a bike?

#### Load datasets and libraries
    chi = read.csv('chicago.csv')
    wash = read.csv('washington.csv')
    ny = read.csv('new-york-city.csv')
    library(ggplot2)
    library(lubridate)
    
#### Create a new dataset for weekday, month, and city for each start time in each city. Weekday Levels: Sun < Mon < Tue < Wed < Thu < Fri < Sat
    month = c(month(chi$Start.Time), month(ny$Start.Time), month(wash$Start.Time))
    wkdy = c(wday(chi$Start.Time), wday(ny$Start.Time), wday(wash$Start.Time))
    city = c(rep("Chicago", times = dim(chi)[1]), rep("New York", times = dim(ny)[1]), 
             rep("Washington", times = dim(wash)[1]))
    all.start = data.frame(month, wkdy, city)

#### Plot the frequency of each weekday
    wday_plot = ggplot(aes(x=wkdy), data = all.start) +
      geom_histogram(stat = 'count', color = 'black', fill = 'blue') +
      scale_x_continuous(breaks = c(1:7), labels = c('Sun','Mon','Tue','Wed','Thu','Fri','Sat'))
    
    wday_plot + ggtitle('Bike Rentals: Weekday') +
      scale_y_continuous(breaks = c(seq(0,150000, 20000)))

#### To get summary statistics, create a frequency table from the weekday data
    tbl_wkdy = table(all.start$wkdy)
    tbl_wkdy
    
#### Get the maximum weekday with max()
    max(tbl_wkdy)
    
#### Results: The chart shows that Wednesdays have had the most bike rentals in all 3 cities combined. The summary statistics show that the highest count of bike rentals is 142,773, which correlates to the count for Wednesdays in the chart. 


## Question 2
###  The bikesharing company might want to make cdecisions based on the most popular day of the week. However, the most popular day
###  of the week may vary from month to month. Does the most popular day of the week vary from month to month? 

#### Plot the frequency of each weekday per month

    wday_plot + facet_wrap(~month) +
    ggtitle('Bike Rentals: Weekday Per Month')
    
#### To get summary statistics, create a frequency table from the weekday and month data.  

    tbl_mo.wday = table(all.start$month, all.start$wkdy)
    tbl_mo.wday

#### Get the maximum weekday (column) per month (row) with max.col()        

    max.col(tbl_mo.wday)

#### Results: The chart shows that the most popular day of the week does vary across months. The summary statistics show that: Wednesday is the most popular day in Jan, Feb, Mar and May; Sunday is the mot popular day in Apr; and Thursday is the most popular day in Jun.


## Question 3
###Does the popular day of the week vary across the 3 cities?**
  
#### Plot the weekday per city       
      wday_plot + facet_wrap(~city) +
      ggtitle('Bike Rentals: Weekday Per City')
    
#### To get summary statistics, create a frequency table from the weekday and city data.
    tbl_cty.wday = table(all.start$city, all.start$wkdy)
    tbl_cty.wday        
    
#### Get the maximum weekday (column) per city (row) with max.col()
    max.col(tbl_cty.wday)

#### Results: The chart shows that New York and Washington both have Wednesday as the most popular day to rent a bike and they both have a similar trend. Chicago does not share the same trend as New York and Washington. the summary statistics confirm that Chicago's most popular day is Tuesday, while New York and Washington's are Wednesday. The bike share company should decide to either further investigate the differences in Chicago or focus weekday-related actions on New York and Washington. 
```
  